import { useMemo, useState } from "react";
import { CalendarDays, ChevronLeft, ChevronRight, Download, Plus, Settings, TriangleAlert, X, Trash2 } from "lucide-react";
import { defaultData } from "./data";
import type { AppData, Availability, CalendarEvent, EventType, Field, Program } from "./types";
const KEY="lax-calendar-v2";
const load=():AppData=>{try{return JSON.parse(localStorage.getItem(KEY) || "") as AppData}catch{return defaultData}};
const key=(d:Date)=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`;
const tmin=(t:string)=>{const [h,m]=t.split(":").map(Number);return h*60+m};
const fmt=(t:string)=>new Date(`2000-01-01T${t}`).toLocaleTimeString("en-US",{hour:"numeric",minute:"2-digit"});
const uid=()=>crypto.randomUUID();
function overlap(a:{startTime:string;endTime:string},b:{startTime:string;endTime:string}){return tmin(a.startTime)<tmin(b.endTime)&&tmin(b.startTime)<tmin(a.endTime)}
function addDays(date:string,days:number){const d=new Date(`${date}T12:00:00`);d.setDate(d.getDate()+days);return key(d)}
function remainingSlots(a:Availability,events:CalendarEvent[]){
 const busy=events.filter(e=>e.date===a.date&&e.fieldId===a.fieldId&&e.type!=="Holiday").map(e=>({start:Math.max(tmin(e.startTime),tmin(a.startTime)),end:Math.min(tmin(e.endTime),tmin(a.endTime))})).filter(x=>x.start<x.end).sort((x,y)=>x.start-y.start);
 const merged:{start:number;end:number}[]=[];
 busy.forEach(x=>{const last=merged[merged.length-1];if(last&&x.start<=last.end)last.end=Math.max(last.end,x.end);else merged.push({...x})});
 const slots:{startTime:string;endTime:string}[]=[];let cursor=tmin(a.startTime);
 for(const b of merged){if(cursor<b.start)slots.push({startTime:`${String(Math.floor(cursor/60)).padStart(2,"0")}:${String(cursor%60).padStart(2,"0")}`,endTime:`${String(Math.floor(b.start/60)).padStart(2,"0")}:${String(b.start%60).padStart(2,"0")}`});cursor=Math.max(cursor,b.end)}
 const end=tmin(a.endTime);if(cursor<end)slots.push({startTime:`${String(Math.floor(cursor/60)).padStart(2,"0")}:${String(cursor%60).padStart(2,"0")}`,endTime:`${String(Math.floor(end/60)).padStart(2,"0")}:${String(end%60).padStart(2,"0")}`});return slots
}
function App(){
 const [data,setData]=useState(load); const [date,setDate]=useState(new Date(2026,8,1)); const [view,setView]=useState<"month"|"week"|"agenda">("month");
 const [programs,setPrograms]=useState<string[]>(data.programs.filter(p=>p.active).map(p=>p.id)); const [fields,setFields]=useState<string[]>(data.fields.filter(f=>f.active).map(f=>f.id));
 const [showAvailable,setShowAvailable]=useState(true); const [eventEdit,setEventEdit]=useState<CalendarEvent|null>(null); const [availEdit,setAvailEdit]=useState<Availability|null>(null); const [manage,setManage]=useState(false);
 const save=(next:AppData)=>{setData(next);localStorage.setItem(KEY,JSON.stringify(next))};
 const pmap=useMemo(()=>new Map(data.programs.map(p=>[p.id,p])),[data.programs]); const fmap=useMemo(()=>new Map(data.fields.map(f=>[f.id,f])),[data.fields]);
 const visibleEvents=data.events.filter(e=>{
  if(!fields.includes(e.fieldId)) return false;
  const special=e.type==="Blackout"||e.type==="Holiday";
  const programVisible=special||!e.programId||programs.includes(e.programId);
  const hasAvailability=data.availability.some(a=>a.date===e.date&&a.fieldId===e.fieldId);
  return programVisible&&(special||hasAvailability);
 });
 const conflicts=useMemo(()=>visibleEvents.filter((e,i)=>visibleEvents.some((o,j)=>i!==j&&e.date===o.date&&e.fieldId===o.fieldId&&overlap(e,o))),[visibleEvents]);
 const monthDays=useMemo(()=>{const first=new Date(date.getFullYear(),date.getMonth(),1);const start=new Date(first);start.setDate(1-first.getDay());return Array.from({length:42},(_,i)=>{const d=new Date(start);d.setDate(start.getDate()+i);return d})},[date]);
 const weekDays=useMemo(()=>{const s=new Date(date);s.setDate(date.getDate()-date.getDay());return Array.from({length:7},(_,i)=>{const d=new Date(s);d.setDate(s.getDate()+i);return d})},[date]);
 const eventConflict=(e:CalendarEvent)=>data.events.some(o=>o.id!==e.id&&o.date===e.date&&o.fieldId===e.fieldId&&overlap(e,o));
 const outsidePermit=(e:CalendarEvent)=>!data.availability.some(a=>a.date===e.date&&a.fieldId===e.fieldId&&tmin(e.startTime)>=tmin(a.startTime)&&tmin(e.endTime)<=tmin(a.endTime));
 const upsertEvent=(e:CalendarEvent,repeatWeeks=1)=>{
  const exists=data.events.some(x=>x.id===e.id);
  if(exists){save({...data,events:data.events.map(x=>x.id===e.id?e:x)});setEventEdit(null);return}
  const series=Array.from({length:repeatWeeks},(_,i)=>({...e,id:i===0?e.id:uid(),date:addDays(e.date,i*7)}));
  save({...data,events:[...data.events,...series]});setEventEdit(null)
 };
 const upsertAvail=(a:Availability)=>{save({...data,availability:data.availability.some(x=>x.id===a.id)?data.availability.map(x=>x.id===a.id?a:x):[...data.availability,a]});setAvailEdit(null)};
 const exportICS=()=>{const lines=["BEGIN:VCALENDAR","VERSION:2.0","PRODID:-//LaxCalendar//EN",...visibleEvents.flatMap(e=>["BEGIN:VEVENT",`UID:${e.id}@laxcalendar`,`DTSTART:${e.date.replaceAll("-","")}T${e.startTime.replace(":","")}00`,`DTEND:${e.date.replaceAll("-","")}T${e.endTime.replace(":","")}00`,`SUMMARY:${e.title.replaceAll(",","\\,")}`,`LOCATION:${(fmap.get(e.fieldId)?.name||"").replaceAll(",","\\,")}`,"END:VEVENT"]),"END:VCALENDAR"];
 const blob=new Blob([lines.join("\r\n")],{type:"text/calendar"});const url=URL.createObjectURL(blob);const a=document.createElement("a");a.href=url;a.download="lacrosse-calendar.ics";a.click();URL.revokeObjectURL(url)};
 const move=(n:number)=>setDate(view==="month"?new Date(date.getFullYear(),date.getMonth()+n,1):new Date(date.getFullYear(),date.getMonth(),date.getDate()+7*n));
 return <div className="app"><header><div><p className="eyebrow">LACROSSE FIELD SCHEDULER</p><h1>Fall 2026</h1></div><div className="actions"><button onClick={()=>setManage(true)}><Settings size={17}/>Programs & Fields</button><button onClick={exportICS}><Download size={17}/>Export ICS</button><button onClick={()=>setAvailEdit({id:uid(),fieldId:data.fields[0]?.id||"",date:key(date),startTime:"09:00",endTime:"15:00"})}><Plus size={17}/>Availability</button><button className="primary" onClick={()=>setEventEdit({id:uid(),programId:data.programs[0]?.id,fieldId:data.fields[0]?.id||"",type:"Practice",title:"",date:key(date),startTime:"17:30",endTime:"19:00"})}><Plus size={17}/>Event</button></div></header>
 <section className="controls"><div className="nav"><button onClick={()=>move(-1)}><ChevronLeft/></button><button onClick={()=>setDate(new Date(2026,8,1))}>Today</button><strong>{date.toLocaleDateString("en-US",{month:"long",year:"numeric"})}</strong><button onClick={()=>move(1)}><ChevronRight/></button></div><div className="views">{(["month","week","agenda"] as const).map(v=><button className={view===v?"active":""} onClick={()=>setView(v)} key={v}>{v[0].toUpperCase()+v.slice(1)}</button>)}</div></section>
 <section className="filters"><div><strong>Programs</strong>{data.programs.filter(p=>p.active).map(p=><label key={p.id}><input type="checkbox" checked={programs.includes(p.id)} onChange={()=>setPrograms(programs.includes(p.id)?programs.filter(x=>x!==p.id):[...programs,p.id])}/><i style={{background:p.color}}/>{p.name}</label>)}</div><div><strong>Fields</strong>{data.fields.filter(f=>f.active).map(f=><label key={f.id}><input type="checkbox" checked={fields.includes(f.id)} onChange={()=>setFields(fields.includes(f.id)?fields.filter(x=>x!==f.id):[...fields,f.id])}/>{f.name}</label>)}</div><label><input type="checkbox" checked={showAvailable} onChange={e=>setShowAvailable(e.target.checked)}/>Show available time</label>{conflicts.length>0&&<span className="warning"><TriangleAlert size={16}/>{conflicts.length} conflicting events</span>}</section>
 <main>{view==="month"&&<Month days={monthDays} date={date} data={data} events={visibleEvents} showAvailable={showAvailable} pmap={pmap} fmap={fmap} onDay={(d:string)=>setEventEdit({id:uid(),programId:data.programs[0]?.id,fieldId:data.fields[0]?.id||"",type:"Practice",title:"",date:d,startTime:"17:30",endTime:"19:00"})} onEvent={setEventEdit} onAvail={setAvailEdit}/>} {view==="week"&&<Week days={weekDays} data={data} events={visibleEvents} pmap={pmap} fmap={fmap} showAvailable={showAvailable} onEvent={setEventEdit} onAvail={setAvailEdit}/>} {view==="agenda"&&<Agenda events={visibleEvents} pmap={pmap} fmap={fmap} onEvent={setEventEdit}/>}</main>
 {eventEdit&&<EventModal event={eventEdit} data={data} conflict={eventConflict(eventEdit)} outside={outsidePermit(eventEdit)} onClose={()=>setEventEdit(null)} onSave={upsertEvent} onDelete={(id:string)=>{save({...data,events:data.events.filter(e=>e.id!==id)});setEventEdit(null)}}/>}
 {availEdit&&<AvailModal item={availEdit} fields={data.fields} onClose={()=>setAvailEdit(null)} onSave={upsertAvail} onDelete={(id:string)=>{save({...data,availability:data.availability.filter(a=>a.id!==id)});setAvailEdit(null)}}/>}
 {manage&&<ManageModal data={data} onClose={()=>setManage(false)} onSave={(next:AppData)=>{save(next);setPrograms(next.programs.filter((p:Program)=>p.active).map((p:Program)=>p.id));setFields(next.fields.filter((f:Field)=>f.active).map((f:Field)=>f.id));setManage(false)}}/>}
 </div>
}
function Month({days,date,data,events,showAvailable,pmap,fmap,onDay,onEvent,onAvail}:any){return <><div className="weekday">{["Sun","Mon","Tue","Wed","Thu","Fri","Sat"].map(x=><div key={x}>{x}</div>)}</div><div className="month">{days.map((d:Date)=>{const k=key(d),ev=events.filter((e:CalendarEvent)=>e.date===k),av=data.availability.filter((a:Availability)=>a.date===k&&data.fields.some((f:Field)=>f.id===a.fieldId&&f.active));return <section className={d.getMonth()===date.getMonth()?"":"muted"} key={k}><button className="day" onClick={()=>onDay(k)}>{d.getDate()}</button>{showAvailable&&av.flatMap((a:Availability)=>remainingSlots(a,events).map((slot,i)=><button className="avail" onClick={()=>onAvail(a)} key={`${a.id}-${i}`}>Available {fmt(slot.startTime)}–{fmt(slot.endTime)}<small>{fmap.get(a.fieldId)?.name}</small></button>))}{ev.map((e:CalendarEvent)=>{const p=e.programId?pmap.get(e.programId):null;return <button className={`event ${(e.type==="Blackout"||e.type==="Holiday")?"blackout":""}`} style={p?{background:p.color}:undefined} onClick={()=>onEvent(e)} key={e.id}><strong>{e.title}</strong><small>{fmt(e.startTime)}–{fmt(e.endTime)}</small></button>})}</section>})}</div></>}
function Week({days,data,events,pmap,fmap,showAvailable,onEvent,onAvail}:any){return <div className="week">{days.map((d:Date)=>{const k=key(d);const visibleFields=data.fields.filter((f:Field)=>{if(!f.active)return false;const hasAvailability=data.availability.some((a:Availability)=>a.date===k&&a.fieldId===f.id);const hasSpecial=events.some((e:CalendarEvent)=>e.date===k&&e.fieldId===f.id&&(e.type==="Holiday"||e.type==="Blackout"));return hasAvailability||hasSpecial});return <section key={k}><h3>{d.toLocaleDateString("en-US",{weekday:"short",month:"short",day:"numeric"})}</h3>{visibleFields.map((f:Field)=>{const av=data.availability.filter((a:Availability)=>a.date===k&&a.fieldId===f.id),ev=events.filter((e:CalendarEvent)=>e.date===k&&e.fieldId===f.id);return <div className="field" key={f.id}><strong>{f.name}</strong>{showAvailable&&av.flatMap((a:Availability)=>remainingSlots(a,events).map((slot,i)=><button className="avail" onClick={()=>onAvail(a)} key={`${a.id}-${i}`}>Available {fmt(slot.startTime)}–{fmt(slot.endTime)}</button>))}{ev.map((e:CalendarEvent)=>{const p=e.programId?pmap.get(e.programId):null;return <button className={`event ${(e.type==="Blackout"||e.type==="Holiday")?"blackout":""}`} style={p?{background:p.color}:undefined} onClick={()=>onEvent(e)} key={e.id}>{fmt(e.startTime)}–{fmt(e.endTime)} · {e.title}</button>})}</div>})}</section>})}</div>}
function Agenda({events,pmap,fmap,onEvent}:any){return <div className="agenda">{[...events].sort((a,b)=>a.date.localeCompare(b.date)||a.startTime.localeCompare(b.startTime)).map((e:CalendarEvent)=>{const p=e.programId?pmap.get(e.programId):null;return <button onClick={()=>onEvent(e)} key={e.id}><span>{new Date(`${e.date}T12:00`).toLocaleDateString("en-US",{weekday:"short",month:"short",day:"numeric"})}</span><i style={{background:p?.color||"#fdecec"}}/><strong>{e.title}</strong><small>{fmt(e.startTime)}–{fmt(e.endTime)} · {fmap.get(e.fieldId)?.name}</small></button>})}</div>}
function EventModal({event,data,conflict,outside,onClose,onSave,onDelete}:any){
 const [d,setD]=useState(event);const [repeat,setRepeat]=useState(1);const set=(k:string,v:any)=>setD({...d,[k]:v});const existing=data.events.some((e:CalendarEvent)=>e.id===d.id);
 const dates=Array.from({length:repeat},(_,i)=>addDays(d.date,i*7));
 const special=d.type==="Blackout"||d.type==="Holiday";
 const outsideDates=special?[]:dates.filter((date:string)=>!data.availability.some((a:Availability)=>a.date===date&&a.fieldId===d.fieldId&&tmin(d.startTime)>=tmin(a.startTime)&&tmin(d.endTime)<=tmin(a.endTime)));
 const conflictDates=dates.filter((date:string)=>data.events.some((e:CalendarEvent)=>e.id!==d.id&&e.date===date&&e.fieldId===d.fieldId&&overlap(e,d)));
 const blocked=outsideDates.length>0||conflictDates.length>0||!d.title;
 return <Modal title="Lacrosse event" onClose={onClose}><div className="form"><label className="wide">Title<input value={d.title} onChange={e=>set("title",e.target.value)}/></label><label>Type<select value={d.type} onChange={e=>set("type",e.target.value)}>{["Practice","Game","Tournament","Clinic","Tryout","Team Event","Holiday","Blackout"].map(x=><option key={x}>{x}</option>)}</select></label><label>Program<select value={d.programId||""} disabled={special} onChange={e=>set("programId",e.target.value||undefined)}><option value="">None</option>{data.programs.filter((p:Program)=>p.active).map((p:Program)=><option value={p.id} key={p.id}>{p.name}</option>)}</select></label><label>Field<select value={d.fieldId} onChange={e=>set("fieldId",e.target.value)}>{data.fields.filter((f:Field)=>f.active).map((f:Field)=><option value={f.id} key={f.id}>{f.name}</option>)}</select></label><label>Date<input type="date" value={d.date} onChange={e=>set("date",e.target.value)}/></label><label>Start<input type="time" value={d.startTime} onChange={e=>set("startTime",e.target.value)}/></label><label>End<input type="time" value={d.endTime} onChange={e=>set("endTime",e.target.value)}/></label>{!existing&&!special&&<label>Repeat weekly<select value={repeat} onChange={e=>setRepeat(Number(e.target.value))}>{[1,2,3,4,5,6,8,10,12].map(n=><option value={n} key={n}>{n===1?"Does not repeat":`${n} weeks`}</option>)}</select></label>}<label className="wide">Notes<textarea rows={3} value={d.notes||""} onChange={e=>set("notes",e.target.value)}/></label></div>{conflict&&repeat===1&&<p className="alert"><TriangleAlert size={16}/>This overlaps another event on the same field.</p>}{outside&&repeat===1&&!special&&<p className="alert"><TriangleAlert size={16}/>This event is outside recorded field availability.</p>}{outsideDates.length>0&&<p className="alert"><TriangleAlert size={16}/>Cannot save: no matching availability on {outsideDates.join(", ")}.</p>}{conflictDates.length>0&&<p className="alert"><TriangleAlert size={16}/>Cannot save: field conflict on {conflictDates.join(", ")}.</p>}<div className="modal-actions"><button className="danger" onClick={()=>onDelete(d.id)}><Trash2 size={16}/>Delete</button><span/><button onClick={onClose}>Cancel</button><button className="primary" disabled={blocked} onClick={()=>onSave(d,repeat)}>Save</button></div></Modal>
}
function AvailModal({item,fields,onClose,onSave,onDelete}:any){const [d,setD]=useState(item);const set=(k:string,v:any)=>setD({...d,[k]:v});return <Modal title="Field availability" onClose={onClose}><div className="form"><label className="wide">Field<select value={d.fieldId} onChange={e=>set("fieldId",e.target.value)}>{fields.filter((f:Field)=>f.active).map((f:Field)=><option value={f.id} key={f.id}>{f.name}</option>)}</select></label><label>Date<input type="date" value={d.date} onChange={e=>set("date",e.target.value)}/></label><label>Start<input type="time" value={d.startTime} onChange={e=>set("startTime",e.target.value)}/></label><label>End<input type="time" value={d.endTime} onChange={e=>set("endTime",e.target.value)}/></label></div><div className="modal-actions"><button className="danger" onClick={()=>onDelete(d.id)}><Trash2 size={16}/>Delete</button><span/><button onClick={onClose}>Cancel</button><button className="primary" onClick={()=>onSave(d)}>Save</button></div></Modal>}
function ManageModal({data,onClose,onSave}:any){const [d,setD]=useState(data);return <Modal title="Programs & fields" onClose={onClose}><h3>Programs</h3>{d.programs.map((p:Program,i:number)=><div className="manage-row" key={p.id}><input type="color" value={p.color} onChange={e=>setD({...d,programs:d.programs.map((x:Program,j:number)=>j===i?{...x,color:e.target.value}:x)})}/><input value={p.name} onChange={e=>setD({...d,programs:d.programs.map((x:Program,j:number)=>j===i?{...x,name:e.target.value}:x)})}/><label><input type="checkbox" checked={p.active} onChange={e=>setD({...d,programs:d.programs.map((x:Program,j:number)=>j===i?{...x,active:e.target.checked}:x)})}/>Active</label></div>)}<button onClick={()=>setD({...d,programs:[...d.programs,{id:uid(),name:"New Program",color:"#f3e8c8",active:true}]})}><Plus size={16}/>Add program</button><h3>Fields</h3>{d.fields.map((f:Field,i:number)=><div className="manage-row fields" key={f.id}><input value={f.name} onChange={e=>setD({...d,fields:d.fields.map((x:Field,j:number)=>j===i?{...x,name:e.target.value}:x)})}/><label><input type="checkbox" checked={f.active} onChange={e=>setD({...d,fields:d.fields.map((x:Field,j:number)=>j===i?{...x,active:e.target.checked}:x)})}/>Active</label></div>)}<button onClick={()=>setD({...d,fields:[...d.fields,{id:uid(),name:"New Field",active:true}]})}><Plus size={16}/>Add field</button><div className="modal-actions"><span/><span/><button onClick={onClose}>Cancel</button><button className="primary" onClick={()=>onSave(d)}>Save</button></div></Modal>}
function Modal({title,onClose,children}:any){return <div className="backdrop"><div className="modal"><div className="modal-title"><h2>{title}</h2><button onClick={onClose}><X/></button></div>{children}</div></div>}
export default App;
